-- Generated by Oracle SQL Developer Data Modeler 24.3.1.347.1153
--   at:        2025-01-19 12:33:44 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE departments (
    department_id INTEGER NOT NULL,
    dep_name          CHAR(100),
    dean_id       INTEGER NOT NULL
);

ALTER TABLE departments ADD CONSTRAINT departments_pk PRIMARY KEY ( department_id );

CREATE TABLE employees (
    employee_id INTEGER NOT NULL,
    emp_name        CHAR(50),
    surname     CHAR(50),
    salary      INTEGER,
    gender      CHAR(1)
);

ALTER TABLE employees ADD CONSTRAINT employees_pk PRIMARY KEY ( employee_id );

CREATE TABLE grades (
    student_id       INTEGER NOT NULL,
    grade_details_id INTEGER NOT NULL,
    test_id          INTEGER NOT NULL
);

CREATE TABLE grades_details (
    grade_id INTEGER NOT NULL,
    grade_date  DATE,
    grade_value    INTEGER
);

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE grade_id_seq';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;
/

CREATE SEQUENCE grade_id_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER trg_grade_id
BEFORE INSERT ON grades_details
FOR EACH ROW
BEGIN
    SELECT grade_id_seq.NEXTVAL INTO :NEW.grade_id FROM dual;
END;
/

ALTER TABLE grades_details ADD CONSTRAINT grades_details_pk PRIMARY KEY ( grade_id );

CREATE TABLE groups (
    group_id    INTEGER NOT NULL,
    subject_id  INTEGER NOT NULL,
    employee_id INTEGER NOT NULL
);

ALTER TABLE groups ADD CONSTRAINT groups_pk PRIMARY KEY ( group_id );

CREATE TABLE majors (
    major_id      INTEGER NOT NULL,
    department_id INTEGER NOT NULL,
    major_name          CHAR(100),
    student_limit INTEGER
);

ALTER TABLE majors ADD CONSTRAINT majors_pk PRIMARY KEY ( major_id );

CREATE TABLE semesters (
    semester_id INTEGER NOT NULL,
    major_id    INTEGER NOT NULL,
    semester_count INTEGER NOT NULL
);

ALTER TABLE semesters ADD CONSTRAINT semesters_pk PRIMARY KEY ( semester_id );

CREATE TABLE student_details (
    student_id INTEGER,
    student_name CHAR(50),
    surname CHAR(50),
    date_start DATE,
    date_end DATE,
    gender CHAR(1)
);

ALTER TABLE student_details ADD CONSTRAINT student_details_pk PRIMARY KEY ( student_id );

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE student_id_seq';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE student_id_seq';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;
/

CREATE SEQUENCE student_id_seq
    START WITH 1
    INCREMENT BY 1;
/


CREATE OR REPLACE TRIGGER trg_student_id
BEFORE INSERT ON student_details
FOR EACH ROW
BEGIN
    SELECT student_id_seq.NEXTVAL INTO :NEW.student_id FROM dual;
END;
/

CREATE TABLE students (
    student_id INTEGER NOT NULL,
    group_id   INTEGER NOT NULL
);


CREATE TABLE subjects (
    subject_id  INTEGER NOT NULL,
    subject_name CHAR(50) NOT NULL,
    ects_count  INTEGER,
    lecturer_id INTEGER NOT NULL,
    semester_id INTEGER NOT NULL
);

ALTER TABLE subjects ADD CONSTRAINT subjects_pk PRIMARY KEY ( subject_id );

CREATE TABLE tests (
    test_id INTEGER NOT NULL,
    test_type    CHAR(20),
    test_date  DATE
);

ALTER TABLE tests ADD CONSTRAINT tests_pk PRIMARY KEY ( test_id );

CREATE TABLE universities (
    university_id             INTEGER,
    departments_department_id INTEGER NOT NULL
);

ALTER TABLE departments
    ADD CONSTRAINT departments_employees_fk FOREIGN KEY ( dean_id )
        REFERENCES employees ( employee_id );

ALTER TABLE grades
    ADD CONSTRAINT grades_grades_details_fk FOREIGN KEY ( grade_details_id )
        REFERENCES grades_details ( grade_id );

ALTER TABLE grades
    ADD CONSTRAINT grades_students_fk FOREIGN KEY ( student_id )
        REFERENCES student_details ( student_id );

ALTER TABLE grades
    ADD CONSTRAINT grades_tests_fk FOREIGN KEY ( test_id )
        REFERENCES tests ( test_id );

ALTER TABLE groups
    ADD CONSTRAINT groups_employees_fk FOREIGN KEY ( employee_id )
        REFERENCES employees ( employee_id );

ALTER TABLE groups
    ADD CONSTRAINT groups_subjects_fk FOREIGN KEY ( subject_id )
        REFERENCES subjects ( subject_id );

ALTER TABLE majors
    ADD CONSTRAINT majors_departments_fk FOREIGN KEY ( department_id )
        REFERENCES departments ( department_id );

ALTER TABLE semesters
    ADD CONSTRAINT semesters_majors_fk FOREIGN KEY ( major_id )
        REFERENCES majors ( major_id );


ALTER TABLE students
    ADD CONSTRAINT students_groups_fk FOREIGN KEY ( group_id )
        REFERENCES groups ( group_id );

ALTER TABLE students
    ADD CONSTRAINT students_details_fk FOREIGN KEY ( STUDENT_ID )
        REFERENCES STUDENT_DETAILS ( STUDENT_ID );

ALTER TABLE subjects
    ADD CONSTRAINT subjects_employees_fk FOREIGN KEY ( lecturer_id )
        REFERENCES employees ( employee_id );

ALTER TABLE subjects
    ADD CONSTRAINT subjects_semesters_fk FOREIGN KEY ( semester_id )
        REFERENCES semesters ( semester_id );

ALTER TABLE universities
    ADD CONSTRAINT universities_departments_fk FOREIGN KEY ( departments_department_id )
        REFERENCES departments ( department_id );



-- Oracle SQL Developer Data Modeler Summary Report:
--
-- CREATE TABLE                            12
-- CREATE INDEX                             0
-- ALTER TABLE                             22
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
--
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
--
-- REDACTION POLICY                         0
--
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
--
-- ERRORS                                   0
-- WARNINGS                                 0